version: '3.7' # Updated version for better networking features

services:

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8070:8080" # Port for Spark master web UI
      - "7077:7077" # Spark master service port
    networks:
      - spark-network

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=4g"
    ports:
      - "8081:8081" # Spark worker web UI port
    networks:
      - spark-network

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=4g"
    ports:
      - "8082:8081"
    networks:
      - spark-network

  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-3
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=4g"
    ports:
      - "8083:8081"
    networks:
      - spark-network

  jupyter-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-pyspark-notebook
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
      - "SPARK_MASTER=spark://spark-master:37077"
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/home/jovyan/work"
      - "./postgresql-42.6.0.jar:/home/jovyan/jars/postgresql-42.6.0.jar"
      - "./movie_titles.txt:/home/jovyan/movie_titles.txt"
    networks:
      - spark-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=exampleuser
      - POSTGRES_PASSWORD=examplepass
      - POSTGRES_DB=netflix
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  postgres_data: {}